/**
 * TypeScript contracts mapped to the Spring Boot backend DTOs.
 * Keep the backend terminology — do not rename these concepts.
 */

export interface Conference {
  id: number;
  shortName: string;
  desiredUserName?: string;
  email: string;
  conferenceDate?: string;
  conferenceEndDate?: string;
  conferenceUrl?: string;
  url?: string;
  status: boolean;
  /** Presentation fields supplied by the backend where available. */
  fullTitle?: string;
  venueName?: string;
  city?: string;
  country?: string;
  phone?: string;
}

export interface AboutConference {
  id: number;
  heading: string;
  summary: string;
  paragraphs: string[];
  highlights: { title: string; description: string }[];
  status: boolean;
}

export interface Track {
  id: number;
  name: string;
  description: string;
  displayOrder: number;
  status: boolean;
}

export interface ImportantDate {
  id: number;
  title: string;
  date: string;
  description?: string;
  displayOrder: number;
  status: boolean;
}

export type SpeakerCategory =
  | "SIGNED_UP"
  | "PLENARY"
  | "KEYNOTE"
  | "INVITED"
  | "YRF"
  | "FEATURED"
  | "DELEGATE"
  | "POSTER"
  | "UNABLE_TO_ATTEND";

export interface Speaker {
  id: number;
  firstName: string;
  lastName: string;
  designation?: string;
  organization?: string;
  country?: string;
  category: SpeakerCategory;
  photoUrl?: string;
  biography?: string;
  status: boolean;
}

export interface CoreCommitteeMember {
  id: number;
  firstName: string;
  lastName: string;
  designation?: string;
  organization?: string;
  country?: string;
  bio?: string;
  photoUrl?: string;
  displayOrder: number;
  status: boolean;
}

export interface WorkshopBanner {
  id: number;
  title: string;
  description?: string;
  imageUrl?: string;
  targetUrl?: string;
  displayOrder: number;
  status: boolean;
}

export type SponsorshipLevel = "PLATINUM" | "GOLD" | "SILVER" | "BRONZE" | "PARTNER";

export interface Sponsor {
  id: number;
  name: string;
  description?: string;
  logoUrl?: string;
  websiteUrl?: string;
  sponsorshipLevel: SponsorshipLevel;
  displayOrder: number;
  status: boolean;
}

export interface MediaPartner {
  id: number;
  name: string;
  description?: string;
  logoUrl?: string;
  websiteUrl?: string;
  displayOrder: number;
  status: boolean;
}

export interface AttendeeFrom {
  id: number;
  name: string;
  displayOrder: number;
  status: boolean;
}

export interface ConferenceFile {
  id: number;
  title: string;
  description?: string;
  fileUrl: string;
  fileType?: string;
  fileSize?: string;
  displayOrder: number;
  status: boolean;
}

export interface ConferenceUpdate {
  id: number;
  title: string;
  body: string;
  publishedAt: string;
  tag?: string;
  status: boolean;
}

export type PresentationType = "ORAL" | "POSTER" | "WORKSHOP" | "OTHER";

export interface AbstractSubmissionRequest {
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | undefined;
  organization?: string | undefined;
  country?: string | undefined;
  abstractTitle: string;
  abstractBody: string;
  keywords?: string | undefined;
  presentationType: PresentationType;
}

export interface AbstractSubmissionResponse {
  abstractNumber: string;
  submissionStatus: string;
  email: string;
}

export interface RegistrationCategory {
  code: string;
  label: string;
  description?: string;
}

export interface RegistrationRequest {
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | undefined;
  organization?: string | undefined;
  designation?: string | undefined;
  country?: string | undefined;
  registrationCategory: string;
  notes?: string | undefined;
  amount?: number | undefined;
  currency?: string | undefined;
  paymentStatus?: string | undefined;
  paymentReference?: string | undefined;
}

export interface RegistrationResponse {
  registrationNumber: string;
  email: string;
  paymentStatus: string;
  paymentReference?: string | undefined;
  amount?: number | undefined;
  currency?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  registrationType?: string | undefined;
  /** Payment link is generated by the backend PaymentProvider abstraction. */
  paymentLink?: string | undefined;
}

export interface VenueInfo {
  name: string;
  address: string;
  city: string;
  country: string;
  mapEmbedUrl?: string;
  nearestAirport?: string;
  transportation: string[];
  travelNotes?: string;
}

export interface Hotel {
  id: number;
  name: string;
  category: string;
  distanceFromVenue: string;
  priceRange?: string;
  notes?: string;
}

export interface ProgramSession {
  id: number;
  time: string;
  title: string;
  type: "KEYNOTE" | "PLENARY" | "SESSION" | "WORKSHOP" | "POSTER" | "BREAK";
  speaker?: string;
  room?: string;
}

export interface ProgramDay {
  id: number;
  label: string;
  date?: string;
  sessions: ProgramSession[];
}

export interface HighlightItem {
  id: number;
  title: string;
  description: string;
}
