/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccommodationRouteImport } from './routes/accommodation'
import { Route as CallForPapersRouteImport } from './routes/call-for-papers'
import { Route as CommitteeRouteImport } from './routes/committee'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SubmitAbstractRouteImport } from './routes/submit-abstract'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TracksRouteImport } from './routes/tracks'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as VenueRouteImport } from './routes/venue'
import { Route as WorkshopsRouteImport } from './routes/workshops'
import { Route as SpeakersIndexRouteImport } from './routes/speakers.index'
import { Route as SpeakersIdRouteImport } from './routes/speakers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationRoute = AccommodationRouteImport.update({
  id: '/accommodation',
  path: '/accommodation',
  getParentRoute: () => rootRouteImport,
} as any)
const CallForPapersRoute = CallForPapersRouteImport.update({
  id: '/call-for-papers',
  path: '/call-for-papers',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeRoute = CommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitAbstractRoute = SubmitAbstractRouteImport.update({
  id: '/submit-abstract',
  path: '/submit-abstract',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueRoute = VenueRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsRoute = WorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersIndexRoute = SpeakersIndexRouteImport.update({
  id: '/speakers/',
  path: '/speakers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersIdRoute = SpeakersIdRouteImport.update({
  id: '/speakers/$id',
  path: '/speakers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/call-for-papers': typeof CallForPapersRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/registration': typeof RegistrationRoute
  '/sponsors': typeof SponsorsRoute
  '/submit-abstract': typeof SubmitAbstractRoute
  '/terms': typeof TermsRoute
  '/tracks': typeof TracksRoute
  '/updates': typeof UpdatesRoute
  '/venue': typeof VenueRoute
  '/workshops': typeof WorkshopsRoute
  '/speakers/$id': typeof SpeakersIdRoute
  '/speakers/': typeof SpeakersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/call-for-papers': typeof CallForPapersRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/registration': typeof RegistrationRoute
  '/sponsors': typeof SponsorsRoute
  '/submit-abstract': typeof SubmitAbstractRoute
  '/terms': typeof TermsRoute
  '/tracks': typeof TracksRoute
  '/updates': typeof UpdatesRoute
  '/venue': typeof VenueRoute
  '/workshops': typeof WorkshopsRoute
  '/speakers/$id': typeof SpeakersIdRoute
  '/speakers': typeof SpeakersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accommodation': typeof AccommodationRoute
  '/call-for-papers': typeof CallForPapersRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/privacy': typeof PrivacyRoute
  '/program': typeof ProgramRoute
  '/registration': typeof RegistrationRoute
  '/sponsors': typeof SponsorsRoute
  '/submit-abstract': typeof SubmitAbstractRoute
  '/terms': typeof TermsRoute
  '/tracks': typeof TracksRoute
  '/updates': typeof UpdatesRoute
  '/venue': typeof VenueRoute
  '/workshops': typeof WorkshopsRoute
  '/speakers/$id': typeof SpeakersIdRoute
  '/speakers/': typeof SpeakersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/accommodation'
    | '/call-for-papers'
    | '/committee'
    | '/contact'
    | '/downloads'
    | '/privacy'
    | '/program'
    | '/registration'
    | '/sponsors'
    | '/submit-abstract'
    | '/terms'
    | '/tracks'
    | '/updates'
    | '/venue'
    | '/workshops'
    | '/speakers/$id'
    | '/speakers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/accommodation'
    | '/call-for-papers'
    | '/committee'
    | '/contact'
    | '/downloads'
    | '/privacy'
    | '/program'
    | '/registration'
    | '/sponsors'
    | '/submit-abstract'
    | '/terms'
    | '/tracks'
    | '/updates'
    | '/venue'
    | '/workshops'
    | '/speakers/$id'
    | '/speakers'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/accommodation'
    | '/call-for-papers'
    | '/committee'
    | '/contact'
    | '/downloads'
    | '/privacy'
    | '/program'
    | '/registration'
    | '/sponsors'
    | '/submit-abstract'
    | '/terms'
    | '/tracks'
    | '/updates'
    | '/venue'
    | '/workshops'
    | '/speakers/$id'
    | '/speakers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AccommodationRoute: typeof AccommodationRoute
  CallForPapersRoute: typeof CallForPapersRoute
  CommitteeRoute: typeof CommitteeRoute
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramRoute: typeof ProgramRoute
  RegistrationRoute: typeof RegistrationRoute
  SponsorsRoute: typeof SponsorsRoute
  SubmitAbstractRoute: typeof SubmitAbstractRoute
  TermsRoute: typeof TermsRoute
  TracksRoute: typeof TracksRoute
  UpdatesRoute: typeof UpdatesRoute
  VenueRoute: typeof VenueRoute
  WorkshopsRoute: typeof WorkshopsRoute
  SpeakersIdRoute: typeof SpeakersIdRoute
  SpeakersIndexRoute: typeof SpeakersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodation': {
      id: '/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AccommodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-for-papers': {
      id: '/call-for-papers'
      path: '/call-for-papers'
      fullPath: '/call-for-papers'
      preLoaderRoute: typeof CallForPapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee': {
      id: '/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof CommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-abstract': {
      id: '/submit-abstract'
      path: '/submit-abstract'
      fullPath: '/submit-abstract'
      preLoaderRoute: typeof SubmitAbstractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue': {
      id: '/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof VenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops': {
      id: '/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof WorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/': {
      id: '/speakers/'
      path: '/speakers'
      fullPath: '/speakers/'
      preLoaderRoute: typeof SpeakersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/$id': {
      id: '/speakers/$id'
      path: '/speakers/$id'
      fullPath: '/speakers/$id'
      preLoaderRoute: typeof SpeakersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AccommodationRoute: AccommodationRoute,
  CallForPapersRoute: CallForPapersRoute,
  CommitteeRoute: CommitteeRoute,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramRoute: ProgramRoute,
  RegistrationRoute: RegistrationRoute,
  SponsorsRoute: SponsorsRoute,
  SubmitAbstractRoute: SubmitAbstractRoute,
  TermsRoute: TermsRoute,
  TracksRoute: TracksRoute,
  UpdatesRoute: UpdatesRoute,
  VenueRoute: VenueRoute,
  WorkshopsRoute: WorkshopsRoute,
  SpeakersIdRoute: SpeakersIdRoute,
  SpeakersIndexRoute: SpeakersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
